name: Build ESP32-S3 Firmware

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    container:
      image: espressif/idf:v5.3

    steps:
      - name: Checkout repository with submodules
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          submodules: 'recursive'

      - name: Build ESP32-S3 Firmware
        run: |
          . /opt/esp/idf/export.sh
          
          git submodule update --init --recursive
          
          idf.py -B build-s3 \
                 -DIDF_TARGET=esp32s3 \
                 -DSDKCONFIG=sdkconfig.s3 \
                 -DSDKCONFIG_DEFAULTS=sdkconfig.defaults.esp32s3 \
                 build esptool_py merge_bin

      - name: Upload Merged Binary
        uses: actions/upload-artifact@v4.6.1
        with:
          name: esp32s3-firmware-merged
          path: build-s3/merged-firmware.bin
